"""Core components for the RAG system."""

from .enums import (
    ChunkingStrategy,
    DistanceMetric,
    EmbeddingProviderType,
    RerankerType,
    RetrievalStrategy,
    VectorBackendType,
)
from .exceptions import (
    ChunkingConfigError,
    ChunkingError,
    DocumentLoadError,
    EmbeddingAuthError,
    EmbeddingDimensionError,
    EmbeddingError,
    EmbeddingProviderError,
    EmbeddingProviderInitError,
    EmbeddingRateLimitError,
    EmbeddingTimeoutError,
    IngestionError,
    IngestionPipelineError,
    RerankingError,
    RetrievalError,
    VectorStoreConnectionError,
    VectorStoreError,
    VectorStoreOperationError,
    VectorStoreSchemaError,
)
from .models import (
    Chunk,
    Document,
    EmbeddingRequest,
    EmbeddingResult,
    RetrievalResult,
)

__all__ = [
    "ChunkingStrategy",
    "DistanceMetric",
    "EmbeddingProviderType",
    "RerankerType",
    "RetrievalStrategy",
    "VectorBackendType",
    # Exceptions
    "ChunkingConfigError",
    "ChunkingError",
    "DocumentLoadError",
    "EmbeddingAuthError",
    "EmbeddingDimensionError",
    "EmbeddingError",
    "EmbeddingProviderError",
    "EmbeddingProviderInitError",
    "EmbeddingRateLimitError",
    "EmbeddingTimeoutError",
    "IngestionError",
    "IngestionPipelineError",
    "RerankingError",
    "RetrievalError",
    "VectorStoreConnectionError",
    "VectorStoreError",
    "VectorStoreOperationError",
    "VectorStoreSchemaError",
    # Models
    "Chunk",
    "Document",
    "EmbeddingRequest",
    "EmbeddingResult",
    "RetrievalResult",
]
